var portfolioData = [
  {
    title: "Simlea",
    role: "I work as a main Flutter developer.",
    description:
      "Take your lead capture to the next level and boost your ROI with SIMLEA®, the go - to digital solution for exhibitions.Whether you're a trade show pro or just getting started, SIMLEA® makes it easy to collect, manage, and use visitor data, all in one simple platform.",
    stack: [
      { title: "Flutter", icon: "devicon-flutter-plain colored" },
      { title: "Dart", icon: "devicon-dart-plain colored" },
      { title: "MaterialUI", icon: "devicon-materialui-plain colored" },
      { title: "Android ", icon: "devicon-android-plain colored" },
      { title: "IOS", icon: "devicon-apple-original colored" },
    ],
    basePath: "img/portfolio/gallery/simlea/",

    cover: "cover.jpg",
    coverIcons: ["fab fa-android", "fab fa-apple"],
    maxImages: 14,
    imagesExtension: "jpeg",
    imagesDirection: "vertical",
    sectionClass: "filter-1",
    delay: "0.1s",
  },
  {
    title: "ePRINTit SaaS",
    role: "I work as a full-stack developer.",
    description:
      " ePRINTit SaaS is an app that allows users to print documents and photos directly from their mobile devices It is compatible with both iOS and Android platforms and allows for printing to any printer. Users can also print from Google drive, Dropbox, Box or onedrive. The app also allows for easy management and tracking of print jobs, as well as the ability to store and share documents.",
    stack: [
      { title: "Ionic", icon: "devicon-ionic-original colored" },
      { title: "Capacitor", icon: "devicon-capacitor-plain colored" },
      { title: "Angular", icon: "devicon-angularjs-plain colored" },
      { title: "Typescript", icon: "devicon-typescript-plain colored" },
      { title: "Android ", icon: "devicon-android-plain colored" },
      { title: "IOS", icon: "devicon-apple-original colored" },
    ],
    basePath: "img/portfolio/gallery/eprint-it/",
    cover: "cover.jpg",
    coverIcons: ["fab fa-android", "fab fa-apple"],
    maxImages: 10,
    imagesExtension: "jpeg",
    imagesDirection: "vertical",
    sectionClass: "filter-1",
    delay: "0.1s",
  },

  {
    title: "DealersBook",
    role: "I work as a full-stack developer.",
    description:
      "Dealers book is a digital book for dealers for keeping their record organised.",
    stack: [
      { title: "Flutter", icon: "devicon-flutter-plain colored" },
      { title: "Dart", icon: "devicon-dart-plain colored" },
      { title: "MaterialUI", icon: "devicon-materialui-plain colored" },
      { title: "Android ", icon: "devicon-android-plain colored" },
      { title: "IOS", icon: "devicon-apple-original colored" },
    ],
    basePath: "img/portfolio/gallery/dealersbook/",
    cover: "cover.jpg",
    coverIcons: ["fab fa-android", "fab fa-apple"],
    maxImages: 5,
    imagesExtension: "png",
    imagesDirection: "vertical",
    sectionClass: "filter-1",
    delay: "0.0s",
  },
  {
    title: "PrinterOn Print",
    role: "I work as a full-stack developer.",
    description:
      "PrinterOn simplifies finding and printing documents to any PrinterOn-supported Enterprise or Public Printing Location, all within a user-friendly application.",
    stack: [
      { title: "Ionic", icon: "devicon-ionic-original colored" },
      { title: "Capacitor", icon: "devicon-capacitor-plain colored" },
      { title: "Angular", icon: "devicon-angularjs-plain colored" },
      { title: "Typescript", icon: "devicon-typescript-plain colored" },
      { title: "Android ", icon: "devicon-android-plain colored" },
      { title: "IOS", icon: "devicon-apple-original colored" },
    ],
    basePath: "img/portfolio/gallery/printer-on-print/",
    cover: "cover.jpg",
    coverIcons: ["fab fa-android", "fab fa-apple"],
    maxImages: 11,
    imagesExtension: "jpeg",
    imagesDirection: "vertical",
    sectionClass: "filter-1",
    delay: "0.0s",
  },
  {
    title: "Assessment Archive",
    role: "I work as a full-stack developer.",
    description:
      " Assessment Archive is an innovative real estate app designed to streamline property management by allowing users to easily upload pictures and videos of properties. It enables users to create detailed property records and add multiple assessments for each property. Even without internet access, the app ensures seamless functionality by allowing offline data saving, with automatic syncing when a connection becomes available",
    stack: [
      { title: "Vue", icon: "devicon-vuejs-plain colored" },
      { title: "Nuxt", icon: "devicon-nuxtjs-plain colored" },
      { title: "Capacitor", icon: "devicon-capacitor-plain colored" },
      { title: "Tailwind", icon: "devicon-tailwindcss-original colored" },
      { title: "SQlite", icon: "devicon-sqlite-plain colored" },
      { title: "Typescript", icon: "devicon-typescript-plain colored" },
      { title: "Android ", icon: "devicon-android-plain colored" },
      { title: "IOS", icon: "devicon-apple-original colored" },
    ],
    basePath: "img/portfolio/gallery/assessment-archive/",
    cover: "cover.jpg",
    coverIcons: ["fab fa-android", "fab fa-apple"],
    maxImages: 6,
    imagesExtension: "jpg",
    imagesDirection: "vertical",
    sectionClass: "filter-1",
    delay: "0.0s",
  },

  {
    title: "PayThePoolMan",
    role: "I work as Ionic/Angular mobile developer.",
    description:
      "Paythepoolman Plus is a cutting-edge mobile application designed to streamline workforce management for businesses while they're on the move. Built with Ionic and Angular, this app is packed with features that allow you to effectively plan and track routes to enhance the quality of service. With Paythepoolman Plus, you can easily manage and monitor your workforce, assign tasks, track progress, and ensure timely completion of work orders",
    stack: [
      { title: "Ionic", icon: "devicon-ionic-original colored" },
      { title: "Capacitor", icon: "devicon-capacitor-plain colored" },
      { title: "Angular", icon: "devicon-angularjs-plain colored" },
      { title: "Typescript", icon: "devicon-typescript-plain colored" },
      { title: "Android ", icon: "devicon-android-plain colored" },
      { title: "IOS", icon: "devicon-apple-original colored" },
    ],
    basePath: "img/portfolio/gallery/pay-the-poolman/",
    cover: "cover.jpg",
    coverIcons: ["fab fa-android", "fab fa-apple"],
    maxImages: 32,
    imagesExtension: "jpeg",
    imagesDirection: "vertical",
    sectionClass: "filter-1",
    delay: "0.0s",
  },
  {
    title: "Try6Degree",
    role: "I work on backend side for writing Supabse edge function for calculating degress of sharing and references.",
    description:
      "6Degrees is a reward calculator website. where the user can come with a reference code and we will reward its referrer with some points. Suppose a referred person refers some other user. All the parents get some reward points as 1st-degree and 2nd-degree points.",
    stack: [
      { title: "Supabase", icon: "devicon-supabase-plain colored" },
      { title: "Typescript", icon: "devicon-typescript-plain colored" },
    ],
    basePath: "img/portfolio/gallery/try6degree/",
    cover: "cover.jpg",
    coverIcons: ["fas fa-laptop"],
    maxImages: 1,
    imagesExtension: "jpg",
    imagesDirection: "vertical",
    sectionClass: "filter-2",
    delay: "0.0s",
  },
  {
    title: "HomeaZZon",
    role: "I work as Ionic/Angular mobile developer.",
    description: `  1. Smart Home Organizer 
                        2. Property Management Tool
                        3. Virtual Home Assistant
                        4. Home Inventory Tracker
                        5. Estate Management App
                        6. Digital Property Log`,
    stack: [
      { title: "Ionic", icon: "devicon-ionic-original colored" },
      { title: "Capacitor", icon: "devicon-capacitor-plain colored" },
      { title: "Angular", icon: "devicon-angularjs-plain colored" },
      { title: "Typescript", icon: "devicon-typescript-plain colored" },
      { title: "Android ", icon: "devicon-android-plain colored" },
      { title: "IOS", icon: "devicon-apple-original colored" },
    ],
    basePath: "img/portfolio/gallery/homezzone/",
    cover: "cover.jpg",
    coverIcons: ["fab fa-android", "fab fa-apple"],
    maxImages: 5,
    imagesExtension: "jpg",
    imagesDirection: "vertical",
    sectionClass: "filter-1",
    delay: "0.0s",
  },
  {
    title: "Voxly",
    role: "I work as a Flutter developer.",
    description:
      "Voxly Tuition provides a new and innovative approach to education.Our efficient teaching methods ensure a successful approach to learning.Our courses ensure that regardless of your child’s abilities they will improve and develop their skills. Our methods work. They are modern and progressive and are designed to bring out the best in your child.Our courses are not only designed for short term growth but also with long term success in mind.",
    stack: [
      { title: "Flutter", icon: "devicon-flutter-plain colored" },
      { title: "Dart", icon: "devicon-dart-plain colored" },
      { title: "MaterialUI", icon: "devicon-materialui-plain colored" },
      { title: "Android ", icon: "devicon-android-plain colored" },
      { title: "IOS", icon: "devicon-apple-original colored" },
    ],
    basePath: "img/portfolio/gallery/voxly/",
    cover: "cover.jpg",
    coverIcons: ["fab fa-android", "fab fa-apple"],
    maxImages: 7,
    imagesExtension: "jpeg",
    imagesDirection: "vertical",
    sectionClass: "filter-1",
    delay: "0.0s",
  },
  {
    title: "Hippocrate",
    role: "I work as a Flutter developer.",
    description:
      "Hippocrates health system is an AI based medical advisor. Users may provide symptoms, ask medical questions and describe conditions in order to get diagnosis advise, including known medication and treatments.",
    stack: [
      { title: "Flutter", icon: "devicon-flutter-plain colored" },
      { title: "Dart", icon: "devicon-dart-plain colored" },
      { title: "MaterialUI", icon: "devicon-materialui-plain colored" },
      { title: "Android ", icon: "devicon-android-plain colored" },
      { title: "IOS", icon: "devicon-apple-original colored" },
    ],
    basePath: "img/portfolio/gallery/hippocrate/",
    cover: "cover.jpg",
    coverIcons: ["fab fa-android", "fab fa-apple"],
    maxImages: 10,
    imagesExtension: "jpeg",
    imagesDirection: "vertical",
    sectionClass: "filter-1",
    delay: "0.0s",
  },
  {
    title: "Raydan Captain",
    role: "I work as a Flutter developer.",
    description:
      "That is a food delivery app. Used by the riders to pick food from our restaurant and delivered to the given address.Raydan online Food ordering application (Home Delivery or Pickup from the Branch or Future Orders)",
    stack: [
      { title: "Flutter", icon: "devicon-flutter-plain colored" },
      { title: "Dart", icon: "devicon-dart-plain colored" },
      { title: "MaterialUI", icon: "devicon-materialui-plain colored" },
      { title: "Android ", icon: "devicon-android-plain colored" },
      { title: "IOS", icon: "devicon-apple-original colored" },
    ],
    basePath: "img/portfolio/gallery/raydan-captain/",
    cover: "cover.jpg",
    coverIcons: ["fab fa-android", "fab fa-apple"],
    maxImages: 5,
    imagesExtension: "jpg",
    imagesDirection: "vertical",
    sectionClass: "filter-1",
    delay: "0.0s",
  },
];
